import InfiniteScrollTrigger from "~/components/InfiniteScrollTrigger";
import Head from "next/head";
import { Loader } from "~/components/Loader";
import { PostList } from "~/components/PostList";
import { api } from "~/utils/api";
import { NewPostLink } from "~/components/NewPostLink";
import { useSession } from "next-auth/react";

export default function Home() {
  const {
    data: postsData,
    refetch,
    fetchNextPage,
    isFetching,
  } = api.post.getRecent.useInfiniteQuery(
    {},
    {
      getNextPageParam: (lastPage) => lastPage.nextCursor,
    }
  );
  const { data } = useSession();

  if (!postsData) {
    return <Loader />;
  }

  return (
    <>
      <Head>
        <title>Knowhow</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {data && <NewPostLink />}
        <PostList
          posts={postsData.pages.map((p) => p.posts).flat(1)}
          refetch={() => {
            void refetch();
          }}
        />
        <InfiniteScrollTrigger
          isFetching={isFetching}
          onScreenEnter={fetchNextPage}
        />
      </main>
    </>
  );
}
